import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Fully autogenerated sidebar from the docs folder structure.
// Control labels, positions, and generated index pages using _category_.json files.
const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;


